export { default as App } from './App'
export { default as Root } from './Root'
export { default as Header } from './header/Header/Header'
export { default as HeaderNav } from './header/HeaderNav/HeaderNav'
export { default as CovidText } from './covid/CovidText'
export { default as StartBtn } from './StartBtn/StartBtn'